### ISSUE TITLE
Add support for Xtensa LX7

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/xtensa-lx-rt#26]
The `ESP32-S2` and `ESP32-S3` are based on Xtensa LX7 processors. In order to build up the bare-metal ecosystem for these devices we will obviously need runtime support.

There appears to be a large amount of overlap between the LX6 and LX7 processors in this regard, so we may need to refactor things a bit and change how we're gating features.

**Comment by MabezDev** [comment]
[In esp-idf](https://github.com/espressif/esp-idf/blob/master/components/freertos/port/xtensa/xtensa_vectors.S), they use pre processor definitions from the [xtensa-overlays](https://github.com/espressif/xtensa-overlays) repo, maybe we could do something similiar.

Short term, if the current lx6 feature just works, lets reuse that until we have a better plan going forward.

**Comment by jessebraham** [comment]
Upon further investigation, it seems these issues _only_ apply to the ESP32-S2.

Using the `unify-xtensa-asm` branch I was able to build for the ESP32 and ESP32-S3, but when building for the ESP-S2 I see the aforementioned error output. Note that in order to do this I had to first add the `#![allow(named_asm_labels)]` attribute to `lib.rs` in `xtensa-lx-rt`.

**Comment by MabezDev** [comment]
Looking a bit further into my approach in #27, there are details we just can't find out from the Rust compiler (technically LLVM) currently. There is also the general xtensa problem that everything can be custom, so there is no standard layout for the vector table etc.

I think a new approach, consuming `core-isa.h` header files from espressif/xtensa-overlays is a more viable option so I'll look into that.
