### ISSUE TITLE
Don't create `__exception` with `xtensa_lx_rt::exception` macro

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/xtensa-lx-rt#38]
Crates like the atomic emulation trap handler need to intercept the exception process to emulate atomics. However, in the case where an exception happens, that cannot be handled by the trap handler, the error needs to be forwarded to some user handler.

## Proposal

- Don't create `__exception` with `xtensa_lx_rt::exception` macro
- Use a fixed name for the user trap handler created with `xtensa_lx_rt::exception`
-  Make the `__default_exception` call the fixed user trap handler
- Provide a default user handler (which will just panic)

By doing the above, the exception can either be generated and passed straight to the user handler, or in the case of the atomic trap handler, for example, the exception will be generated, and checked. If it's not something the atomic trap can handle it will be passed onto the user handler.

## Alternatives

We do nothing, and instead replicate the proc-macro inside the trap handler crate, e.g `#[xtensa_atomic_emulation_trap::exception]`. This isn't great because if a user forgets to use the `#[xtensa_atomic_emulation_trap::exception]` macro instead of `#[xtensa_lx_rt::exception]`, atomic emulation will stop working.

Thoughts?

cc: @jessebraham  @bjoernQ

**Comment by bjoernQ** [comment]
I think that should work

I was thinking if we could somehow provide a mechanism to have an "exception interceptor chain" where multiple crates can hook in and optionally take over the exception handling - but I can't think of a future use-case where we would need such flexibility
