### ISSUE TITLE
WindowUnderflow4 text size is too large

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/xtensa-lx-rt#49]
I've been testing the LLD linker and it's more strict around the size of sections. In esp-hal, it fails to link blaming this line here: https://github.com/esp-rs/xtensa-lx-rt/blob/654c9302a4f2c615cc5e19a226a39b597f25eadd/exception-esp32.x.jinja#L63 which gets filled into 128, meaning the size of WindowUnderflow4 must be 64 bytes or less.

Here is the output from the section info of WindowOverflow4
```
Section Headers:
[Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
[34] .WindowOverflow4. PROGBITS        00000000 00023c 000012 00  AX  0   0  4
[35] .WindowUnderflow4 PROGBITS        00000000 000250 000040 00  AX  0   0  4
[36] .rela.WindowUnder RELA            00000000 0015c4 000024 0c   I 120  35  4
```

0x40 + 0x12 = 82 bytes, which is > 64.

Interestingly I modified the linker script locally to increase the size of this section to 82 bytes and it still failed, I kept increasing it till it reached 93 bytes and it started working...

AFAIK know, and @bjoernQ may be able to confirm this, the window exceptions came straight from esp-idf (which came from cadence) and should slot in perfectly. There is even a comment which says as much inside the Underflow4 handler which makes me wonder where this is going wrong.

**Comment by bjoernQ** [comment]
Yes I remember I compared the code of the window exceptions a couple of times with what esp-idf uses - it's the same code

**Comment by MabezDev** [comment]
Actually, I think I was a bit too fast! Firstly I misread Overflow :facepalm:, but I also compared the output with GNU LD and the output is the same but it links fine. Finally, I reduced the size of the section by one byte locally and got the same error I've been getting LLD so I think GCC is just as strict.

Back to the drawing board...
